import { createRequire } from 'module';
const require = createRequire(import.meta.url);

// Import template helpers (CommonJS module)
const helpers = require('./scripts/templates/helpers.js');
const dizionarioMap = require('./scripts/templates/dizionario-map.json');

export default function(eleventyConfig) {
  // Ignore directories and files that shouldn't be processed as templates
  eleventyConfig.ignores.add(".planning/**");
  eleventyConfig.ignores.add("node_modules/**");
  eleventyConfig.ignores.add("scripts/**");
  eleventyConfig.ignores.add("build/**");
  eleventyConfig.ignores.add("NOTION_WEBSITE/**");
  eleventyConfig.ignores.add(".claude/**");
  eleventyConfig.ignores.add(".git/**");
  // Ignore root-level markdown files (documentation, not website content)
  eleventyConfig.ignores.add("*.md");
  eleventyConfig.ignores.add("CLAUDE.md");

  // Ignore any remaining static document HTML files (safety net)
  // All document pages should be generated by Liquid pagination templates
  // Note: documenti-questura.html (landing page) is intentionally excluded from this ignore block
  // because it starts with 'documenti-' but is a static page that must be served as-is.
  // This block is kept for safety in case other static documenti-*.html files re-appear.
  const fs = require('fs');
  const path = require('path');
  const pagesDir = path.join(process.cwd(), 'src', 'pages');

  try {
    const files = fs.readdirSync(pagesDir);
    const docFiles = files.filter(f =>
      f.startsWith('documenti-') && f.endsWith('.html') && f !== 'documenti-questura.html'
    );
    for (const file of docFiles) {
      eleventyConfig.ignores.add(`src/pages/${file}`);
    }
    if (docFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${docFiles.length} static document files (replaced by Liquid templates)`);
    }
  } catch (e) {
    // Directory might not exist in some environments
  }

  // All document pages are generated via Liquid pagination templates
  // (documents-primo.liquid, documents-rinnovo.liquid, documents-redirects.liquid).
  // Old static documenti-*.html files were removed in Phase 42.1.
  // Old static permesso-*.html files were removed in Phase 44.1-03.

  // Register Liquid filters for template helpers
  // Used in document page templates for linking to dizionario, formatting, etc.

  /**
   * linkToDizionario - Converts document name to HTML with dizionario links
   * Usage in templates: {{ documentName | linkToDizionario | safe }}
   */
  eleventyConfig.addFilter("linkToDizionario", helpers.linkToDizionario);

  /**
   * normalizeDocumentName - Normalize document names (capitalize, fix spacing)
   * Usage: {{ documentName | normalizeDocumentName }}
   */
  eleventyConfig.addFilter("normalizeDocumentName", helpers.normalizeDocumentName);

  /**
   * getDocumentClass - Return CSS class for document item
   * Usage: {{ documentName | getDocumentClass }}
   */
  eleventyConfig.addFilter("getDocumentClass", helpers.getDocumentClass);

  /**
   * isDisputed - Check if document is disputed (varies by Questura)
   * Usage: {% if documentName | isDisputed %}...{% endif %}
   */
  eleventyConfig.addFilter("isDisputed", helpers.isDisputed);

  /**
   * escapeHtml - Escape HTML special characters to prevent XSS
   * Usage: {{ text | escapeHtml }}
   */
  eleventyConfig.addFilter("escapeHtml", helpers.escapeHtml);

  /**
   * parseDocNotes - Parse document notes into Q&A sections
   * Usage: {% assign sections = docNotes | parseDocNotes %}
   */
  eleventyConfig.addFilter("parseDocNotes", helpers.parseDocNotes);

  /**
   * getSectionBorderColor - Return border color for permit Q&A section cards
   * Based on question keywords, with index-based fallback for variety
   * Usage: {{ section.index | getSectionBorderColor: section.question }}
   */
  eleventyConfig.addFilter("getSectionBorderColor", function(index, question) {
    const q = (question || '').toLowerCase();

    // Match by keywords first
    if (q.includes("cos'è") || q.includes("che cos'è") || q.includes("che cosa")) return 'var(--accent-blue)';
    if (q.includes('requisiti') || q.includes('chi può') || q.includes('chi puo')) return 'var(--taxi-yellow)';
    if (q.includes('lavorare') || q.includes('lavoro') || q.includes('diritti')) return 'var(--lighthouse-red)';
    if (q.includes('conversione') || q.includes('convertire')) return 'var(--accent-teal)';
    if (q.includes('durata') || q.includes('quanto dura')) return 'var(--accent-blue)';
    if (q.includes('costi') || q.includes('quanto costa')) return 'var(--accent-orange)';

    // Fallback by index for variety
    const colors = [
      'var(--accent-blue)',
      'var(--taxi-yellow)',
      'var(--lighthouse-red)',
      'var(--accent-teal)',
      'var(--accent-purple)',
      'var(--accent-orange)'
    ];
    return colors[index % colors.length];
  });

  // Passthrough copy for asset directories
  eleventyConfig.addPassthroughCopy("src/styles");
  eleventyConfig.addPassthroughCopy("src/scripts");
  eleventyConfig.addPassthroughCopy("src/components");
  eleventyConfig.addPassthroughCopy("src/data");
  eleventyConfig.addPassthroughCopy("IMAGES");
  eleventyConfig.addPassthroughCopy("public");

  // Note: EN site uses IT assets via absolute paths (/src/styles, etc.)
  // No separate en/src/styles, en/src/scripts, etc. directories exist

  // Passthrough copy for root-level files
  eleventyConfig.addPassthroughCopy("robots.txt");
  eleventyConfig.addPassthroughCopy("sitemap-it.xml");
  eleventyConfig.addPassthroughCopy("sitemap-en.xml");
  eleventyConfig.addPassthroughCopy("sitemap-index.xml");
  eleventyConfig.addPassthroughCopy("netlify.toml");

  return {
    dir: {
      input: ".",
      output: "_site",
      includes: "_includes"
    },
    templateFormats: ["html", "liquid", "md"],
    htmlTemplateEngine: "liquid"
  };
}
