import { createRequire } from 'module';
const require = createRequire(import.meta.url);

// Import template helpers (CommonJS module)
const helpers = require('./scripts/templates/helpers.js');
const dizionarioMap = require('./scripts/templates/dizionario-map.json');

export default function(eleventyConfig) {
  // Ignore directories and files that shouldn't be processed as templates
  eleventyConfig.ignores.add(".planning/**");
  eleventyConfig.ignores.add("node_modules/**");
  eleventyConfig.ignores.add("scripts/**");
  eleventyConfig.ignores.add("build/**");
  eleventyConfig.ignores.add("NOTION_WEBSITE/**");
  eleventyConfig.ignores.add(".claude/**");
  eleventyConfig.ignores.add(".git/**");
  // Ignore root-level markdown files (documentation, not website content)
  eleventyConfig.ignores.add("*.md");
  eleventyConfig.ignores.add("CLAUDE.md");

  // Ignore any remaining static document HTML files (safety net)
  // All document pages should be generated by Liquid pagination templates
  const fs = require('fs');
  const path = require('path');
  const pagesDir = path.join(process.cwd(), 'src', 'pages');

  try {
    const files = fs.readdirSync(pagesDir);
    const docFiles = files.filter(f =>
      f.startsWith('documenti-') && f.endsWith('.html') && f !== 'documenti-questura.html'
    );
    for (const file of docFiles) {
      eleventyConfig.ignores.add(`src/pages/${file}`);
    }
    if (docFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${docFiles.length} static document files (replaced by Liquid templates)`);
    }
  } catch (e) {
    // Directory might not exist in some environments
  }

  // Same safety net for EN document pages
  const enPagesDir = path.join(process.cwd(), 'en', 'src', 'pages');
  try {
    const enFiles = fs.readdirSync(enPagesDir);
    const enDocFiles = enFiles.filter(f =>
      f.startsWith('documenti-') && f.endsWith('.html')
    );
    for (const file of enDocFiles) {
      eleventyConfig.ignores.add(`en/src/pages/${file}`);
    }
    if (enDocFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${enDocFiles.length} static EN document files (replaced by Liquid templates)`);
    }
    // Safety net for EN static permit pages (fixes DuplicatePermalinkOutputError)
    const enPermitFiles = enFiles.filter(f =>
      f.startsWith('permesso-') && f.endsWith('.html')
    );
    for (const file of enPermitFiles) {
      eleventyConfig.ignores.add(`en/src/pages/${file}`);
    }
    if (enPermitFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${enPermitFiles.length} static EN permit files (replaced by Liquid templates)`);
    }
  } catch (e) {
    // Directory might not exist
  }

  // Safety net for FR document and permit pages
  const frPagesDir = path.join(process.cwd(), 'fr', 'src', 'pages');
  try {
    const frFiles = fs.readdirSync(frPagesDir);
    const frDocFiles = frFiles.filter(f =>
      f.startsWith('documenti-') && f.endsWith('.html')
    );
    for (const file of frDocFiles) {
      eleventyConfig.ignores.add(`fr/src/pages/${file}`);
    }
    if (frDocFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${frDocFiles.length} static FR document files (replaced by Liquid templates)`);
    }
    const frPermitFiles = frFiles.filter(f =>
      f.startsWith('permesso-') && f.endsWith('.html')
    );
    for (const file of frPermitFiles) {
      eleventyConfig.ignores.add(`fr/src/pages/${file}`);
    }
    if (frPermitFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${frPermitFiles.length} static FR permit files (replaced by Liquid templates)`);
    }
  } catch (e) {
    // Directory might not exist yet
  }

  // Safety net for ES document and permit pages
  const esPagesDir = path.join(process.cwd(), 'es', 'src', 'pages');
  try {
    const esFiles = fs.readdirSync(esPagesDir);
    const esDocFiles = esFiles.filter(f =>
      f.startsWith('documenti-') && f.endsWith('.html')
    );
    for (const file of esDocFiles) {
      eleventyConfig.ignores.add(`es/src/pages/${file}`);
    }
    if (esDocFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${esDocFiles.length} static ES document files (replaced by Liquid templates)`);
    }
    const esPermitFiles = esFiles.filter(f =>
      f.startsWith('permesso-') && f.endsWith('.html')
    );
    for (const file of esPermitFiles) {
      eleventyConfig.ignores.add(`es/src/pages/${file}`);
    }
    if (esPermitFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${esPermitFiles.length} static ES permit files (replaced by Liquid templates)`);
    }
  } catch (e) {
    // Directory might not exist yet
  }

  // Safety net for TR document and permit pages
  const trPagesDir = path.join(process.cwd(), 'tr', 'src', 'pages');
  try {
    const trFiles = fs.readdirSync(trPagesDir);
    const trDocFiles = trFiles.filter(f =>
      f.startsWith('documenti-') && f.endsWith('.html')
    );
    for (const file of trDocFiles) {
      eleventyConfig.ignores.add(`tr/src/pages/${file}`);
    }
    if (trDocFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${trDocFiles.length} static TR document files (replaced by Liquid templates)`);
    }
    const trPermitFiles = trFiles.filter(f =>
      f.startsWith('permesso-') && f.endsWith('.html')
    );
    for (const file of trPermitFiles) {
      eleventyConfig.ignores.add(`tr/src/pages/${file}`);
    }
    if (trPermitFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${trPermitFiles.length} static TR permit files (replaced by Liquid templates)`);
    }
  } catch (e) {
    // Directory might not exist yet
  }

  // Safety net for BN document and permit pages
  const bnPagesDir = path.join(process.cwd(), 'bn', 'src', 'pages');
  try {
    const bnFiles = fs.readdirSync(bnPagesDir);
    const bnDocFiles = bnFiles.filter(f =>
      f.startsWith('documenti-') && f.endsWith('.html')
    );
    for (const file of bnDocFiles) {
      eleventyConfig.ignores.add(`bn/src/pages/${file}`);
    }
    if (bnDocFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${bnDocFiles.length} static BN document files (replaced by Liquid templates)`);
    }
    const bnPermitFiles = bnFiles.filter(f =>
      f.startsWith('permesso-') && f.endsWith('.html')
    );
    for (const file of bnPermitFiles) {
      eleventyConfig.ignores.add(`bn/src/pages/${file}`);
    }
    if (bnPermitFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${bnPermitFiles.length} static BN permit files (replaced by Liquid templates)`);
    }
  } catch (e) {
    // Directory might not exist yet
  }

  // Safety net for RU document and permit pages
  const ruPagesDir = path.join(process.cwd(), 'ru', 'src', 'pages');
  try {
    const ruFiles = fs.readdirSync(ruPagesDir);
    const ruDocFiles = ruFiles.filter(f =>
      f.startsWith('documenti-') && f.endsWith('.html')
    );
    for (const file of ruDocFiles) {
      eleventyConfig.ignores.add(`ru/src/pages/${file}`);
    }
    if (ruDocFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${ruDocFiles.length} static RU document files (replaced by Liquid templates)`);
    }
    const ruPermitFiles = ruFiles.filter(f =>
      f.startsWith('permesso-') && f.endsWith('.html')
    );
    for (const file of ruPermitFiles) {
      eleventyConfig.ignores.add(`ru/src/pages/${file}`);
    }
    if (ruPermitFiles.length > 0) {
      console.log(`[eleventy] Ignoring ${ruPermitFiles.length} static RU permit files (replaced by Liquid templates)`);
    }
  } catch (e) {
    // Directory might not exist yet
  }

  // All document pages are generated via Liquid pagination templates
  // (documents-primo.liquid, documents-rinnovo.liquid).
  // All permit pages are generated via permits.liquid.

  // Register Liquid filters for template helpers
  // Used in document page templates for linking to dizionario, formatting, etc.

  /**
   * linkToDizionario - Converts document name to HTML with dizionario links
   * Usage in templates: {{ documentName | linkToDizionario | safe }}
   */
  eleventyConfig.addFilter("linkToDizionario", helpers.linkToDizionario);

  /**
   * normalizeDocumentName - Normalize document names (capitalize, fix spacing)
   * Usage: {{ documentName | normalizeDocumentName }}
   */
  eleventyConfig.addFilter("normalizeDocumentName", helpers.normalizeDocumentName);

  /**
   * getDocumentClass - Return CSS class for document item
   * Usage: {{ documentName | getDocumentClass }}
   */
  eleventyConfig.addFilter("getDocumentClass", helpers.getDocumentClass);

  /**
   * isDisputed - Check if document is disputed (varies by Questura)
   * Usage: {% if documentName | isDisputed %}...{% endif %}
   */
  eleventyConfig.addFilter("isDisputed", helpers.isDisputed);

  /**
   * escapeHtml - Escape HTML special characters to prevent XSS
   * Usage: {{ text | escapeHtml }}
   */
  eleventyConfig.addFilter("escapeHtml", helpers.escapeHtml);

  /**
   * parseDocNotes - Parse document notes into Q&A sections
   * Usage: {% assign sections = docNotes | parseDocNotes %}
   */
  eleventyConfig.addFilter("parseDocNotes", helpers.parseDocNotes);

  /**
   * getSectionBorderColor - Return border color for permit Q&A section cards
   * Based on question keywords, with index-based fallback for variety
   * Usage: {{ section.index | getSectionBorderColor: section.question }}
   */
  eleventyConfig.addFilter("getSectionBorderColor", function(index, question) {
    const q = (question || '').toLowerCase();

    // Match by keywords first
    if (q.includes("cos'è") || q.includes("che cos'è") || q.includes("che cosa")) return 'var(--accent-blue)';
    if (q.includes('requisiti') || q.includes('chi può') || q.includes('chi puo')) return 'var(--taxi-yellow)';
    if (q.includes('lavorare') || q.includes('lavoro') || q.includes('diritti')) return 'var(--lighthouse-red)';
    if (q.includes('conversione') || q.includes('convertire')) return 'var(--accent-teal)';
    if (q.includes('durata') || q.includes('quanto dura')) return 'var(--accent-blue)';
    if (q.includes('costi') || q.includes('quanto costa')) return 'var(--accent-orange)';

    // Fallback by index for variety
    const colors = [
      'var(--accent-blue)',
      'var(--taxi-yellow)',
      'var(--lighthouse-red)',
      'var(--accent-teal)',
      'var(--accent-purple)',
      'var(--accent-orange)'
    ];
    return colors[index % colors.length];
  });

  // Passthrough copy for asset directories
  eleventyConfig.addPassthroughCopy("src/styles");
  eleventyConfig.addPassthroughCopy("src/scripts");
  eleventyConfig.addPassthroughCopy("src/components");
  eleventyConfig.addPassthroughCopy("src/data");
  eleventyConfig.addPassthroughCopy("IMAGES");
  eleventyConfig.addPassthroughCopy("public");

  // Note: EN site uses IT assets via absolute paths (/src/styles, etc.)
  // No separate en/src/styles, en/src/scripts, etc. directories exist

  // Passthrough copy for root-level files
  eleventyConfig.addPassthroughCopy("robots.txt");
  // Note: sitemap-it.xml, sitemap-en.xml, sitemap-fr.xml, sitemap-index.xml are now
  // generated by 11ty Liquid templates (src/pages/sitemap-*.liquid), not passthrough copies.
  eleventyConfig.addPassthroughCopy("netlify.toml");

  return {
    dir: {
      input: ".",
      output: "_site",
      includes: "_includes"
    },
    templateFormats: ["html", "liquid", "md"],
    htmlTemplateEngine: "liquid"
  };
}
